Linking the Drupal install to the php dir should be the last step in the build.
Guard against the deploy hook running if the build hook partially failed.

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -60,17 +60,6 @@ else
   echo "Drupal is already installed at $DRUPAL_INSTALL_DIR"
 fi
 
-#
-# OpenShift looks for PHP files inside of app-root/runtime/repo/php
-# This runs on every build to ensure that the link is present (since
-# repo is recreated)
-#
-if ! ln -s $DRUPAL_INSTALL_DIR ${OPENSHIFT_REPO_DIR}php
-then
-  echo "ERROR: Unable to link the PHP directory"
-  exit 8
-fi
-
 echo
 
 #
@@ -81,4 +70,15 @@ if [ ! -d "$DRUPAL_SITE_DIR" ]
 then
   cp -r $DRUPAL_INSTALL_DIR/sites.original $DRUPAL_SITE_DIR
   ln -s $DRUPAL_SITE_DIR $DRUPAL_INSTALL_DIR/sites
+fi
+
+#
+# OpenShift looks for PHP files inside of app-root/runtime/repo/php
+# This runs on every build to ensure that the link is present (since
+# repo is recreated)
+#
+if ! ln -s $DRUPAL_INSTALL_DIR ${OPENSHIFT_REPO_DIR}php
+then
+  echo "ERROR: Unable to link the PHP directory, Drupal cannot be used if the php directory already exists in your Git repository."
+  exit 8
 fi
diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -12,6 +12,12 @@ DRUPAL_SETTINGS=${DRUPAL_SITE_DIR}/default/settings.php
 DRUSH_SCRIPT=${OPENSHIFT_DATA_DIR}bin/drush
 DEFAULT_PASSWORD=openshift_changeme
 
+if [ ! -d "${DRUPAL_SITE_DIR}/default" ]
+then
+  echo "No sites directory has been created, Drupal cannot be deployed"
+  exit 9
+fi
+
 #
 # Create a new Drupal site.  You can delete your ${OPENSHIFT_DATA_DIR}sites
 # folder to run this step again.
